# 服务名称
Spring:
  application:
    name: micr-dataservice
  redis:
    port: 6379
    host: 192.168.56.104

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.104:3306/ylbdb?userUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: mrying
    password: 123456

# 设置 MyBatis
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 配置 dubbo
dubbo:
    registry:
      address: zookeeper://192.168.56.104:2181

    scan:
      base-packages: org.example.ylb.dataservice.service

    provider:
      timeout: 50000
      retries: 0

# 密码加“盐”
salt: 8464cffca803189e878b340ba83424d7

