# 服务名称
Spring:
  application:
    name: micr-dataservice

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.233.209:3306/ylbdb?userUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: mrying
    password: 123456

# 设置 MyBatis
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 配置 dubbo
dubbo:
    registry:
      address: zookeeper://localhost:2181

    scan:
      base-packages: org.example.ylb.dataservice.service

    provider:
      timeout: 50000
      retries: 0

