spring:
  application:
    name: micr-web

# 端口号
server:
  port: 8000
  servlet:
    context-path: /api
    encoding:
      enabled: true
      charset: UTF-8
      force: true

# 配置 dubbo
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: org.example.ylb.front
  consumer:
    check: false
    timeout: 50000
    retries: 0


