spring:
  application:
    name: micr-web
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: 192.168.56.104

# 端口号
server:
  port: 8000
  servlet:
    context-path: /api
    encoding:
      enabled: true
      charset: UTF-8
      force: true

# 配置 dubbo
dubbo:
  registry:
    address: zookeeper://192.168.56.104:2181
    timeout: 50000
  scan:
    base-packages: org.example.ylb.front
  consumer:
    check: false
    timeout: 50000
    retries: 0

# 短信服务配置项
api:
  sms:
    host: https://gyytz.market.alicloudapi.com
    path: /sms/smsSend
    method: POST
    appCode: b94e4bc6c5da44309ca6ae789acc1a77
    smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
    templateId: 908e94ccf08b4476ba6c876d13f084ad

# JWT 配置
jwt:
  data:
    # jwt加密密钥
    secret: 2bc1a2207c684d7fb29df11f8abdc815
    # jwt储存的请求头Authorization固定写法
    tokenHeader: Authorization
    # jwt的过期时间(60s*60min*24h*7day)
    expiration: 604800
    # jwt负载中拿到的头信息
    tokenHead: Bearer




